general:
  train_pickle_dir: /storage/user/lyun/vivid/vxp_vivid_training_pair_3d_student_p10_n25.pickle ## Training row ID in annotation.csv, note that this is not the picke you train the teacher network
  val_pickle_dir: /storage/user/lyun/vivid/vxp_vivid_testing_pair_3d_student_p10_n25.pickle ## Testing row ID in annotation.csv, note that this is not the picke you train the teacher network
  annotation_dir: /storage/group/dataset_mirrors/01_incoming/vividpp/driving_full/annotations_all.csv ## Location of the annotation.csv
  save_dir: /storage/user/lyun/vivid/ ## Location to save the model and log
  name: vxp_vivid

model:
  teacher_setup: /storage/user/lyun/vivid/models/setup_teacher_vivid_2023_11_20_21_35_31.yml
  teacher_model: /storage/user/lyun/vivid/models/teacher_vivid_2023_11_20_21_35_31_v.pth
  load_pretrained: True
  # student_pretrained_setup: /storage/user/lyun/vivid/models/setup_vxp_local_vivid_wo_invd_2024_03_10_20_42_51.yml
  # student_pretrained_model: /storage/user/lyun/vivid/models/vxp_local_vivid_wo_invd_2024_03_10_20_42_51.pth
  student_pretrained_setup: /storage/user/lyun/vivid/models/setup_vxp_local_vivid_jim_coors_2023_11_22_01_09_16.yml
  student_pretrained_model: /storage/user/lyun/vivid/models/vxp_local_vivid_jim_coors_2023_11_22_01_09_16.pth
  arch: VXIGeM
  parameters:
    up_voxel_size: null
    v2i_pcd_range: null
    device: null
    p: 3
    eps: 0.000001
    normalize: False
    dense_output_dim: !!python/tuple [384, 256]

dataset:
  batch_size: 16
  num_workers: 8
  voxelization: True
  random_horizontal_mirroring_p: 0.5
  pcd_coordinate_transformation:
    OnlinePointAffineTransformation:
      parameters:
        x_axis:
          - -0.02706162
          - 0.01903198
          - -0.99945258
        y_axis:
          - 0.99963206
          - -0.00133414
          - -0.02709189
        z_axis:
          - -0.00184903
          - -0.99981799
          - -0.01898888
        trans:
          - -0.38352616
          - -0.38655251
          - -0.03873405
    OnlineRotZ:
      parameters:
        angle: -90
        use_degree: true
    OnlineRotX:
      parameters:
        angle: 90
        use_degree: true
  pcd_preprocessing:
    OnlineVoxelization:
      parameters:
        {
          point_cloud_range: [0, -22, -4, 44, 22, 18],
          max_num_points: 35,
          voxel_size: [0.4, 0.4, 0.2],
          max_voxels: 10000,
        }
      # parameters: {point_cloud_range: [0, -20, -2.5, 50, 20, 15], max_num_points: 35, voxel_size: [0.75, 0.2, 0.0875], max_voxels: 10000} ## grid size 67 x 200 x 200
  pcd_data_augmentation:
    # {}
    DataAugmentationRandomRigidBodyTransformation:
      parameters:
        {
          x_limit: 1.5,
          y_limit: 1.5,
          z_limit: 1.5,
          pitch_limit: 2,
          yaw_limit: 10,
          roll_limit: 2,
        }
  img_data_augmentation:
    ColorJitter:
      parameters: { brightness: 0.1, contrast: 0.1, saturation: 0.1, hue: 0.1 }
    RandomAffine:
      parameters: { degrees: [-5, 5], translate: [0.1, 0.1] }
loss:
  fn: SmoothL1Loss ## MSELoss
  parameters: { reduction: "mean" }

optimizer:
  fn: Adam
  parameters:
    lr: 1.0e-04
    weight_decay: 1.0e-06
  epochs: 30
  min_lr: 5.0e-06

scheduler:
  fn: LambdaLR
  parameters: { step_size: 2, gamma: 0.95 }
