general:
  name: vivid_city_nightevening
  annotation: /storage/group/dataset_mirrors/01_incoming/vividpp/driving_full/annotations_all.csv
  # save_dir: YOUR_SAVE_DIR
  save_dir: /storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs
  sequence:
    - city_night
    - city_evening
parameter:
  threshold: 25
  yaw: True
  num_samples: 1500
