parameter:
  name: kitti_vxp
  annotation: /storage/user/lyun/kitti/all_annotation.csv
  save_dir: /storage/user/lyun/kitti
  train: [3, 4, 5, 6, 7, 8, 9, 10]
  val: [0, 2]
  val_region:
    p:
      0:
        [
          [613180, 4116330],
          [613050, 4116230],
          [613050, 4116570],
          [613135, 4116455],
        ]
      2:
        [
          [619375, 4116915],
          [619400, 4116800],
          [619400, 4116700],
          [619390, 4116450],
        ]
    width: 50
  pos_th: 10
  neg_th: 25
  yaw: True
