parameter:
  base_dir: /storage/group/dataset_mirrors/01_incoming/Oxford_RobotCar/
  save_dir: /storage/user/lyun/Oxford_Robocar_test/
  ins_dir: null ## Only needed when GPS are saved in different directory
  lidar_dir: null ## Only needed when lidar scans are saved in different directory
  cam_central: False
  max_depth: 50.0
  max_lateral: 25.0
  max_vertical: 25.0
  depth_at_least: 30.0
  every_x_meter: 5.0
  plane_error_threshold: 0.1
  ransac_threshold: 0.2
  ransac_iteration: 1000
  save_submap_with_ground: False
  write_to_annotation: True
sequence: []
