general:
  name: vivid_day12
  annotation: /storage/group/dataset_mirrors/01_incoming/vividpp/driving_full/annotations_all.csv
  # save_dir: YOUR_SAVE_DIR
  save_dir: /storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs
  sequence:
    - day1
    - day2
parameter:
  threshold: 25
  yaw: True
  num_samples: null
  interval: 20
