general:
  name: vivid_day1evening
  annotation: /storage/group/dataset_mirrors/01_incoming/vividpp/driving_full/annotations_all.csv
  # annotation: /storage/user/lyun/vivid/all_annotation.csv
  save_dir: /storage/user/lyun/vivid
  sequence:
    - day1
    - evening
parameter:
  threshold: 25
  yaw: True
  num_samples: null
  interval: 20
