general:
  name: new_vivid_campus_nightday2
  # annotation: /storage/group/dataset_mirrors/01_incoming/vividpp/driving_full/annotations_all.csv
  annotation: /storage/user/lyun/vivid/all_annotation.csv
  save_dir: /storage/user/lyun/vivid
  sequence:
    - campus_night
    - campus_day2
parameter:
  threshold: 25
  yaw: True
  num_samples: 1500
  interval: null
