general:
  name: kitti_00
  student_setup: /usr/stud/lyun/vxp/assets/paper_weights/kitti/setup_vxp_pcnetwork_kitti_2024_01_09_16_57_28.yml
  student_model: /usr/stud/lyun/vxp/assets/paper_weights/kitti/vxp_pcnetwork_kitti_2024_01_09_16_57_28.pth
  query: /storage/user/lyun/kitti/kitti_00_test_region_evaluation_query_th20m_yaw_1runs.pickle
  db: /storage/user/lyun/kitti/kitti_00_test_region_evaluation_database_th20m_yaw_1runs.pickle
  k: 100
  disp_img_tb: False
  cross_normalize: False
  save_dir: /storage/user/lyun/kitti
  num_workers: 4
  batch_size: 16
  rebase_dir: null
  sequence:
    - 0
