general:
  name: oxford
  teacher_setup: /storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs/models/setup_teacher2d_backbone2d_dino_vits8_gem_linear_p10n25yaw_2023_11_09_01_36_28.yml
  teacher_model: /storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs/models/teacher2d_backbone2d_dino_vits8_gem_linear_p10n25yaw_2023_11_09_01_36_28_last.pth
  student_setup: /storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs/models/setup_vxpgem_w_teacher_p10n25yaw_2023_11_11_00_43_31.yml
  student_model: /storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs/models/vxpgem_w_teacher_p10n25yaw_2023_11_11_00_43_31.pth
  # Full dataset 5m query / 5m database 23 runs threshold 20m with yaw
  query: "/storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs/full_q5_db5_evaluation_query_th20m_yaw_23runs.pickle"
  db: "/storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs/full_q5_db5_evaluation_database_th20m_yaw_23runs.pickle"
  disp_img_tb: False
  cross_normalize: True
  save_dir: "/storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs"
  k: 25
  num_workers: 4
  batch_size: 16
  rebase_dir: null
  sequence:
    - 2014-11-14-16-34-33 ## night
    - 2014-11-18-13-20-12 ## clouds, sun
    - 2014-12-02-15-30-08 ## overcast
    - 2014-12-09-13-21-02 ## overcast
    - 2014-12-10-18-10-50 ## night
    - 2014-12-12-10-45-15 ## overcast
    - 2014-12-16-09-14-09 ## sun
    - 2014-12-16-18-44-24 ## night
    - 2015-02-03-08-45-10 ## snow
    - 2015-02-10-11-58-05 ## overcast
    - 2015-02-13-09-16-26 ## overcast
    - 2015-02-17-14-42-12 ## sun
    - 2015-03-10-14-18-10 ## roadworks, sun
    - 2015-03-17-11-08-44 ## overcast
    - 2015-05-19-14-06-38 ## overcast
    - 2015-06-09-15-06-29 ## detour, overcast, roadworks
    - 2015-08-12-15-04-18 ## sun
    - 2015-08-13-16-02-58 ## overcast
    - 2015-08-14-14-54-57 ## overcast, roadworks
    - 2015-08-28-09-50-22 ## sun
    - 2015-10-30-13-52-14 ## overcast
    - 2015-11-12-11-22-05 ## roadworks, sun
    - 2015-11-13-10-28-08 ## overcast, sun
