general:
  name: vivid_campus_nightday2
  student_setup: /usr/stud/lyun/vxp/assets/paper_weights/vivid/setup_vxp_pcnetwork_vivid_2023_11_22_11_34_37.yml
  student_model: /usr/stud/lyun/vxp/assets/paper_weights/vivid/vxp_vxp_pcnetwork_vivid_2023_11_22_11_34_37.pth

  query: /storage/user/lyun/vivid/new_vivid_campus_nightday2_evaluation_query_th25m_yaw_2runs_everyNonem.pickle
  db: /storage/user/lyun/vivid/new_vivid_campus_nightday2_evaluation_database_th25m_yaw_2runs_everyNonem.pickle
  k: 25
  disp_img_tb: False
  cross_normalize: False
  save_dir: "/storage/user/lyun/Oxford_Robocar/dataset_every_5m_45runs"
  num_workers: 4
  batch_size: 16
  rebase_dir: null
  sequence:
    - campus_night
    - campus_day2
