general:
  name: vivid_nightevening
  student_setup: /usr/stud/lyun/vxp/assets/paper_weights/vivid/setup_vxp_pcnetwork_vivid_2023_11_22_11_34_37.yml
  student_model: /usr/stud/lyun/vxp/assets/paper_weights/vivid/vxp_vxp_pcnetwork_vivid_2023_11_22_11_34_37.pth

  query: /storage/user/lyun/vivid/vivid_nightevening_evaluation_query_th25m_yaw_2runs_every20m.pickle
  db: /storage/user/lyun/vivid/vivid_nightevening_evaluation_database_th25m_yaw_2runs_every20m.pickle
  k: 10
  disp_img_tb: False
  cross_normalize: False
  save_dir: "/storage/user/lyun/vivid"
  num_workers: 4
  batch_size: 16
  rebase_dir: null
  sequence:
    - night
    - evening
